### PR TITLE
Split out effect lib

### PR DESCRIPTION
**Pull request by isovector**
This PR teases apart the reusable pieces of the current TH machinery. Doing so allows us to build other TH abstractions in polysemy --- such as an RPC effect.

Todo:

- [x] Haddock

### CODE REVIEW

**Comment by isovector** [comment]
The RPC stuff should live in the zoo, but I wanted to make sure the EffectLib changes were finished before moving it there.

**Comment by isovector** [comment]
@TheMatten what do you think?

**Comment by TheMatten** [comment]
Seems fine. And that RPC effect is interesting 🙂
When it comes to name for that newly created module - if it's going to contain more shared code for different purposes, maybe something like `Polysemy.Internal.TH.Common` could work.

**Comment by isovector** [comment]
I'm wondering if maybe this stuff shouldn't live in its own package at the end of the day --- `polysemy-th`, and then move everything there.

**Comment by TheMatten** [comment]
So you are thinking about possibility to use `polysemy` without TH and it's dependencies?

**Comment by isovector** [comment]
This PR teases apart the reusable pieces of the current TH machinery. Doing so allows us to build other TH abstractions in polysemy --- such as an RPC effect.

**Pull request merged**
